### ISSUE TITLE
P2 | Hardcoding of IP Address and CSV file? in EdgeKernel.rb

### ISSUE THREAD

**Issue by bitvijays** [cm16161/Unikernel-Serverless#5]
Hey Chetan,

Currently, `EdgeKernel.rb` contains hard-coded of IP Address 

```
def check_webdis()
  uri = URI('http://192.168.1.213:7379/GET/hello')
```

and CSV

```
              puts "SPAWNING " + kernel
              val =  `ps -o rss= -p #{$$}`.to_i
              CSV.open("/tmp/top-kek.csv","a") do |csv|
                csv << [val,(val - start_mem)/n_kernels,n_kernels]
              end
```

Either create a global variable to define two variables which contain these values or see if there's a ruby code to get the eth0 ipaddress? 

Regards,
Vijay

**Comment by cm16161** [comment]
Removed the CSV code (was only needed for testing/evaluation) and updated the ``hard-coded" IP Address so less changes need to be made

**Comment by bitvijays** [comment]
Thank you Chetan :) This looks good :)
